name: GitHub Actions Runner in Docker - Base
on:
  push:
    paths:
      - Dockerfile.base
      - .github/workflows/base.yml
      - goss*
    branches:
      - master
      - develop
  schedule:
    - cron:  '0 22 * * *'

jobs:
  base_tests:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        release: [ubuntu-noble]
        platform: [amd64, arm64]
      fail-fast: false
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Get GitHub organization or user
        run: echo 'ORG='$(echo $(dirname ${GITHUB_REPOSITORY}) | awk '{print tolower($0)}') >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Get OS and release
        run: |
          echo "OS=$(echo ${{ matrix.release }} | cut -d'-' -f1)" >> $GITHUB_ENV
          echo "RELEASE=$(echo ${{ matrix.release }} | cut -d'-' -f2)" >> $GITHUB_ENV
      - name: Copy Dockerfile
        run: cp Dockerfile.base Dockerfile.base.${{ matrix.release }}; sed -i.bak 's/FROM.*/FROM ${{ env.OS }}:${{ env.RELEASE }}/' Dockerfile.base.${{ matrix.release }}
      - name: Install Goss and dgoss
        run: |
          curl -fsSL https://goss.rocks/install | sh
          export PATH=$PATH:/usr/local/bin
      - name: Get current Git SHA
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: set testable image environment variable
        id: testvars
        run: echo "GH_RUNNER_IMAGE=${{ matrix.release }}-${{ env.GIT_SHA }}-${{ matrix.platform }}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Retry build and load
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: |
            docker buildx build \
              --file Dockerfile.base.${{ matrix.release }} \
              --platform linux/${{ matrix.platform }} \
              --tag ${{ env.GH_RUNNER_IMAGE }} \
              --load \
              --pull \
              --cache-from type=gha \
              --cache-to type=gha,mode=max \
              --secret id=github_token,env=GITHUB_TOKEN \
              .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run goss tests
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: |
            echo "os: ${{ env.OS }}" >goss_vars_${GH_RUNNER_IMAGE}.yaml
            echo "oscodename: ${{ env.RELEASE }}" >>goss_vars_${GH_RUNNER_IMAGE}.yaml
            echo "arch: ${{ matrix.platform }}" >>goss_vars_${GH_RUNNER_IMAGE}.yaml
            GOSS_VARS=goss_vars_${GH_RUNNER_IMAGE}.yaml GOSS_FILE=goss_base.yaml GOSS_SLEEP=1 dgoss run --entrypoint /usr/bin/sleep -e RUNNER_NAME=test -e DEBUG_ONLY=true ${GH_RUNNER_IMAGE} 10
            if [ $? -ne 0 ]; then
              exit 1
            fi

  base_latest_deploy:
    runs-on: [self-hosted, linux]
    needs: base_tests
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Get GitHub organization or user
        run: echo 'ORG='$(echo $(dirname ${GITHUB_REPOSITORY}) | awk '{print tolower($0)}') >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Login to DockerHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Retry build and push
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: |
            docker buildx build \
              --file Dockerfile.base \
              --platform linux/amd64,linux/arm64 \
              --tag ${{ env.ORG }}/github-runner-base:latest \
              --push \
              --pull \
              --cache-from type=gha \
              --cache-to type=gha,mode=max \
              --secret id=github_token,env=GITHUB_TOKEN \
              .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  base_deploy:
    runs-on: [self-hosted, linux]
    needs: base_tests
    strategy:
      matrix:
        release: [ubuntu-noble]
      fail-fast: false
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Get GitHub organization or user
        run: echo 'ORG='$(echo $(dirname ${GITHUB_REPOSITORY}) | awk '{print tolower($0)}') >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Get OS and release
        run: |
          echo "OS=$(echo ${{ matrix.release }} | cut -d'-' -f1)" >> $GITHUB_ENV
          echo "RELEASE=$(echo ${{ matrix.release }} | cut -d'-' -f2)" >> $GITHUB_ENV
      - name: Copy Dockerfile
        run: cp Dockerfile.base Dockerfile.base.${{ matrix.release }}; sed -i.bak 's/FROM.*/FROM ${{ env.OS }}:${{ env.RELEASE }}/' Dockerfile.base.${{ matrix.release }}
      - name: Login to DockerHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Retry build and push
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: |
            docker buildx build \
              --file Dockerfile.base.${{ matrix.release }} \
              --platform linux/amd64,linux/arm64 \
              --tag ${{ env.ORG }}/github-runner-base:${{ matrix.release }} \
              --push \
              --pull \
              --cache-from type=gha \
              --cache-to type=gha,mode=max \
              --secret id=github_token,env=GITHUB_TOKEN \
              .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}